# This file helps to know what the valid values for each field are.
# Please update it if you add new features.

tool_materials:
  $string:
    base: STRING # WOOD, STONE, IRON, DIAMOND, GOLD, NETHERITE, etc.
    durability: integer
    speed: float
    attack_damage_bonus: float
    enchantment_value: integer
    repair_item: identifier # namespace:id (ex: lost_engine:ingot)

items:
  $string: # item id (generated identifier would be lost_engine:id)
    type: STRING # generic, sword, shovel, pickaxe, axe, hoe

    # Only for sword, shovel, pickaxe, axe and hoe
    attack_damage: float
    attack_speed: float
    material: STRING

    # Components
    enchantment_glint_override: boolean
    fire_resistant: boolean
    food:
      nutrition: integer
      saturation_modifier: float
      can_always_eat: boolean
      consumeSeconds: float
    max_damage: integer
    max_stack_size: integer # (1-99)
    rarity: STRING # COMMON, UNCOMMON, RARE, EPIC
    tooltip_display:
      hide_tooltip: boolean
      hidden_components:
        - STRING # Minecraft component (ex: enchantments, attribute_modifiers)
    unbreakable: boolean
    use_cooldown:
      cooldown_seconds: float
      group: string # You most likely don't need this, it will be generated automatically

    # Resource pack generation
    model: string # either model or texture
    texture: string
    name:
      $string: string # locale: display name (ex: en_US:Iron Sword)

blocks:
  $string: # block id (generated identifier would be lost_engine:id)
    type: STRING # regular, tnt
    drops:
      type: STRING # self, ore
      # Only for ore
      item: identifier
      max: integer
      min: integer

    # Only for regular
    required_material: STRING # WOOD, STONE, IRON, DIAMOND, NETHERITE, NONE
    destroy_time: float
    explosion_resistance: float
    tool_type: STRING # AXE, HOE, PICKAXE, SHOVEL, NONE

    # Only for tnt
    explosion_power: float

    # Resource pack generation
    texture: string
    name:
      $string: string # locale: display name (ex: en_US:Note Block)