package dev.lost.engine;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import dev.lost.annotations.NotNull;
import dev.lost.annotations.Nullable;
import dev.lost.engine.assetsgenerators.*;
import dev.lost.engine.blocks.customblocks.CustomBlock;
import dev.lost.engine.utils.FileUtils;
import dev.lost.furnace.files.model.Model;
import dev.lost.furnace.files.texture.Texture;
import dev.lost.furnace.files.unknown.UnknownFile;
import dev.lost.furnace.resourcepack.BedrockResourcePack;
import dev.lost.furnace.resourcepack.JavaResourcePack;
import dev.lost.furnace.resourcepack.ResourcePack;
import dev.misieur.fast.FastBufferedImage;
import it.unimi.dsi.fastutil.ints.Int2CharOpenHashMap;
import it.unimi.dsi.fastutil.ints.IntArrayList;
import net.kyori.adventure.key.Key;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.block.Block;
import org.bukkit.configuration.ConfigurationSection;
import org.intellij.lang.annotations.Pattern;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Locale;
import java.util.Optional;
import java.util.stream.Stream;

@SuppressWarnings("PatternValidation") // Stupid thing I don't even know why it's here
public class ResourcePackBuilder {

    // TODO: Clean up this class
    public static void buildResourcePack(@NotNull LostEngine plugin, File resourcePackFile, File bedrockResourcePackFile, @Nullable LostEngineMappingGenerator mappingGenerator) throws IOException {
        JavaResourcePack resourcePack = ResourcePack.java();
        BedrockResourcePack bedrockResourcePack = plugin.getConfig().getBoolean("geyser_compatibility", false)
                ? ResourcePack.bedrock() :
                null;

        resourcePack.mcmeta(75, "LostEngine Resource Pack");
        if (bedrockResourcePack != null)
            bedrockResourcePack.manifest("LostEngine Resource Pack", "Resource pack generated by LostEngine for Geyser compatibility.");

        LangFileGenerator langFileGenerator = new LangFileGenerator();
        PaintingItemJsonGenerator paintingItemJsonGenerator = new PaintingItemJsonGenerator();
        File resourceFolder = new File(plugin.getDataFolder(), "resources");
        List<FileUtils.ItemConfig> configs = FileUtils.yamlFiles(resourceFolder);
        BlockStateGenerator blockStateGenerator = new BlockStateGenerator();
        configs.forEach(config -> {
            ConfigurationSection itemsSection = config.config().getConfigurationSection("items");
            if (itemsSection != null) {
                for (String key : itemsSection.getKeys(false)) {
                    ConfigurationSection itemSection = itemsSection.getConfigurationSection(key);
                    if (itemSection != null) {
                        String type = itemSection.getString("type", "generic").toLowerCase();
                        if (type.equals("trident")) {
                            String textureName = itemSection.getString("texture");
                            String iconTextureName = itemSection.getString("icon");
                            if (textureName != null && iconTextureName != null) {
                                createThrowingTridentModel(
                                        resourcePack,
                                        Key.key("lost_engine", "item/" + key + "_throwing"),
                                        Key.key("lost_engine", textureName)
                                );
                                createInHandTridentModel(
                                        resourcePack,
                                        Key.key("lost_engine", "item/" + key + "_trident_in_hand"),
                                        Key.key("lost_engine", textureName)
                                );
                                createItemModel(
                                        resourcePack,
                                        Key.key("lost_engine", "item/" + key),
                                        Key.key("item/generated"),
                                        Key.key("lost_engine", iconTextureName)
                                );
                                createTridentItemFile(
                                        resourcePack,
                                        "assets/lost_engine/items/" + key + ".json",
                                        "lost_engine:item/" + key,
                                        "lost_engine:item/" + key + "_throwing",
                                        "lost_engine:item/" + key + "_trident_in_hand",
                                        paintingItemJsonGenerator,
                                        "lost_engine:" +  key + "_painting"
                                );
                                if (bedrockResourcePack != null) {
                                    createBedrockTextureData(bedrockResourcePack, "textures/" + textureName, key);
                                }
                            }
                        } else {
                            String modelName = itemSection.getString("model");
                            if (modelName != null) {
                                if (bedrockResourcePack != null)
                                    plugin.getSLF4JLogger().warn("Custom item models are not supported in Bedrock resource packs yet: {}", modelName);
                                String namespace = FileUtils.getFirstResourceSubfolder(resourceFolder, config.file());
                                File modelFile = new File(resourceFolder, namespace + "/assets/models/" + modelName);
                                modelFile = FileUtils.detectFileExtension(modelFile, List.of(".json", ".lomodel"));
                                if (modelFile.exists() && modelFile.isFile()) {
                                    if (modelFile.getName().endsWith(".json")) {
                                        createItemFile(
                                                resourcePack,
                                                "assets/lost_engine/items/" + key + ".json",
                                                "lost_engine:" + modelName.replaceAll("\\.json", ""),
                                                paintingItemJsonGenerator,
                                                "lost_engine:" +  key + "_painting"
                                        );
                                    } else if (modelFile.getName().endsWith(".lomodel")) {
                                        plugin.getSLF4JLogger().error("LOModel format is not supported for item models yet: {}", modelFile.getAbsolutePath());
                                    } else {
                                        plugin.getSLF4JLogger().error("Unknown model file for item model: {}", modelFile.getAbsolutePath());
                                    }
                                } else {
                                    plugin.getSLF4JLogger().error("Model file for item model not found: {}", modelFile.getAbsolutePath());
                                }
                            } else {
                                String textureName = itemSection.getString("icon");
                                if (textureName != null) {
                                    createItemModel(
                                            resourcePack,
                                            Key.key("lost_engine", "item/" + key),
                                            switch (type) {
                                                case "sword", "pickaxe", "axe", "shovel", "hoe" ->
                                                        Key.key("item/handheld");
                                                default -> Key.key("item/generated");
                                            },
                                            Key.key("lost_engine", textureName)
                                    );
                                    createItemFile(
                                            resourcePack,
                                            "assets/lost_engine/items/" + key + ".json",
                                            "lost_engine:item/" + key,
                                            paintingItemJsonGenerator,
                                            "lost_engine:" +  key + "_painting"
                                    );
                                    if (bedrockResourcePack != null) {
                                        createBedrockTextureData(bedrockResourcePack, "textures/" + textureName, key);
                                    }
                                }
                            }
                        }
                        ConfigurationSection nameSection = itemSection.getConfigurationSection("name");
                        if (nameSection != null) {
                            nameSection.getKeys(false).forEach(langCode -> {
                                String name = nameSection.getString(langCode);
                                if (name != null) {
                                    langFileGenerator.addTranslation(langCode, "item.lost_engine." + key, name);
                                }
                            });
                        }
                        if (bedrockResourcePack != null && type.equals("armor")) {
                            String armorType = itemSection.getString("armor_type", "chestplate");
                            String material = itemSection.getString("material");
                            if (material == null) {
                                LostEngine.logger().error("Armor material not specified for item {}.", key);
                                continue;
                            }
                            bedrockResourcePack.jsonFile("attachables/lost_engine." + key + ".json", JsonParser.parseString("""
                                            {
                                                "format_version": "1.8.0",
                                                "minecraft:attachable": {
                                                    "description": {
                                                        "identifier": "lost_engine:%s",
                                                        "materials": {
                                                            "default": "armor",
                                                            "enchanted": "armor_enchanted"
                                                        },
                                                        "textures": {
                                                            "enchanted": "textures/misc/enchanted_actor_glint",
                                                            "default": "textures/entity/equipment/%s/%s"
                                                        },
                                                        "geometry": {
                                                            "default": "%s"
                                                        },
                                                        "scripts": {
                                                            "parent_setup": "v.%s_layer_visible = 0.0;"
                                                        },
                                                        "render_controllers": ["controller.render.armor"]
                                                    }
                                                }
                                            }
                                            """.formatted(
                                            key.toLowerCase(Locale.ROOT),
                                            armorType.equals("leggings") ? "humanoid_leggings" : "humanoid",
                                            material.toLowerCase(Locale.ROOT),
                                            switch (armorType) {
                                                case "chestplate" -> "geometry.player.armor.chestplate";
                                                case "leggings" -> "geometry.humanoid.armor.leggings";
                                                case "helmet" -> "geometry.player.armor.helmet";
                                                case "boots" -> "geometry.player.armor.boots";
                                                default ->
                                                        throw new IllegalStateException("Unexpected value for armor type: " + armorType);
                                            },
                                            switch (armorType) {
                                                case "chestplate" -> "chest";
                                                case "leggings" -> "leg";
                                                case "helmet" -> "helmet";
                                                case "boots" -> "boot";
                                                default ->
                                                        throw new IllegalStateException("Unexpected value for armor type: " + armorType);
                                            }
                                    )
                            ));
                        }
                        ConfigurationSection elytraSection = itemSection.getConfigurationSection("elytra");
                        if (elytraSection != null) {
                            String texture = elytraSection.getString("texture");
                            if (texture != null)
                                resourcePack.jsonFile("assets/lost_engine/equipment/%s.json".formatted(key.toLowerCase(Locale.ROOT)), JsonParser.parseString("""
                                        {
                                          "layers": {
                                            "wings": [
                                              {
                                                "texture": "lost_engine:%s",
                                                "use_player_texture": %b
                                              }
                                            ]
                                          }
                                        }
                                        """.formatted(texture, elytraSection.getBoolean("use_player_skin", false))));
                        }
                    }
                }
            }
            ConfigurationSection blocksSection = config.config().getConfigurationSection("blocks");
            if (blocksSection != null) {
                for (String key : blocksSection.getKeys(false)) {
                    ConfigurationSection blockSection = blocksSection.getConfigurationSection(key);
                    if (blockSection != null) {
                        String textureName = blockSection.getString("texture", null);
                        if (textureName != null) {
                            createBlockModel(
                                    resourcePack,
                                    Key.key("lost_engine", "block/" + key),
                                    Key.key("lost_engine", textureName)
                            );
                            createItemFile(
                                    resourcePack,
                                    "assets/lost_engine/items/" + key + ".json",
                                    "lost_engine:block/" + key,
                                    paintingItemJsonGenerator,
                                    "lost_engine:" +  key + "_painting"
                            );
                            Identifier resourceLocation = Identifier.parse("lost_engine:" + key);
                            if (BuiltInRegistries.BLOCK.containsKey(resourceLocation)) {
                                Block block = BuiltInRegistries.BLOCK.getValue(resourceLocation);
                                if (block instanceof CustomBlock customBlock) {
                                    blockStateGenerator.addBlockState(customBlock.getClientBlockState(), "lost_engine:block/" + key);
                                    Optional.ofNullable(customBlock.getNotClickableBlockState()).ifPresent(blockState ->
                                            blockStateGenerator.addBlockState(blockState, "lost_engine:block/" + key)
                                    );
                                }
                            }
                        }
                        ConfigurationSection nameSection = blockSection.getConfigurationSection("name");
                        if (nameSection != null) {
                            nameSection.getKeys(false).forEach(langCode -> {
                                String name = nameSection.getString(langCode);
                                if (name != null) {
                                    langFileGenerator.addTranslation(langCode, "item.lost_engine." + key, name);
                                }
                            });
                        }
                    }
                }
            }
            ConfigurationSection materialsSection = config.config().getConfigurationSection("materials");
            if (materialsSection != null) {
                for (String key : materialsSection.getKeys(false)) {
                    ConfigurationSection materialSection = materialsSection.getConfigurationSection(key);
                    if (materialSection != null) {
                        String armorTexture = materialSection.getString("armor.texture", null);
                        if (armorTexture != null) {
                            resourcePack.jsonFile("assets/lost_engine/equipment/%s.json".formatted(key.toLowerCase(Locale.ROOT)), JsonParser.parseString("""
                                    {
                                      "layers": {
                                        "humanoid": [
                                          {
                                            "texture": "lost_engine:%s"
                                          }
                                        ],
                                        "humanoid_leggings": [
                                          {
                                            "texture": "lost_engine:%s"
                                          }
                                        ]
                                      }
                                    }
                                    """.formatted(armorTexture, armorTexture)));
                        }
                    }
                }
            }
        });
        File[] files = resourceFolder.listFiles();
        if (files != null) {
            for (File file : files) {
                if (file.isDirectory()) {
                    File texturesDir = new File(file, "assets/textures");
                    if (texturesDir.exists() && texturesDir.isDirectory()) {
                        addTexturesRecursively(resourcePack, bedrockResourcePack, texturesDir, "lost_engine");
                    }
                }
            }
        }
        buildGlyphs(plugin, resourcePack, bedrockResourcePack, langFileGenerator, configs);
        langFileGenerator.build(resourcePack, mappingGenerator);
        blockStateGenerator.build(resourcePack);
        paintingItemJsonGenerator.build(resourcePack);

        resourcePack.build(resourcePackFile, dev.lost.furnace.resourcepackbuilder.ResourcePackBuilder.BuildOptions.MAX_COMPRESSION);
        if (bedrockResourcePack != null) {
            bedrockResourcePack.build(
                    bedrockResourcePackFile,
                    dev.lost.furnace.resourcepackbuilder.ResourcePackBuilder.BuildOptions.MAX_COMPRESSION
            );
        }
    }

    public static void buildGlyphs(@NotNull LostEngine plugin, @NotNull ResourcePack resourcePack, @Nullable BedrockResourcePack bedrockResourcePack, @NotNull LangFileGenerator langFileGenerator, @NotNull List<FileUtils.ItemConfig> configs) {
        char c = 57344;
        JsonArray providers = new JsonArray();
        if (plugin.getConfig().getBoolean("resource_pack.glyphs.offset_characters.enabled", false)) {
            int from = plugin.getConfig().getInt("resource_pack.glyphs.offset_characters.from", -1023);
            int to = plugin.getConfig().getInt("resource_pack.glyphs.offset_characters.to", 1023);
            int maxExp = 0;
            while ((1 << (maxExp + 1)) <= Math.max(Math.abs(from), Math.abs(to))) {
                maxExp++;
            }
            IntArrayList offsets = new IntArrayList();

            for (int exp = 0; exp <= maxExp; exp++) {
                int value = 1 << exp;
                if (-value >= from) offsets.add(-value);
                if (value <= to) offsets.add(value);
            }
            offsets.sort(null);
            Int2CharOpenHashMap characters = new Int2CharOpenHashMap();
            JsonObject providerObject = new JsonObject();
            providerObject.addProperty("type", "space");
            JsonObject advancesObject = new JsonObject();
            for (int offset : offsets) {
                if (c >= 63743) {
                    throw new RuntimeException("Exceeded maximum number of glyphs (6400)");
                }
                advancesObject.addProperty(String.valueOf(c), offset);
                characters.addTo(offset, c);
                c++;
            }
            providerObject.add("advances", advancesObject);
            providers.add(providerObject);
            for (int i = from; i <= to; i++) {
                int remaining = i;
                StringBuilder sb = new StringBuilder();

                for (int j = offsets.size() - 1; j >= 0; j--) {
                    int off = offsets.getInt(j);
                    if (remaining == 0) break;
                    if ((remaining > 0 && off > 0 && (remaining & off) == off) ||
                            (remaining < 0 && off < 0 && ((-remaining) & (-off)) == -off)) {
                        sb.append(characters.get(off));
                        remaining -= off;
                    }
                }
                langFileGenerator.addTranslation("en_us", "offsets." + i, sb.toString(), LangFileGenerator.Edition.JAVA);
            }
        }
        BedrockFontGenerator bedrockFontGenerator = bedrockResourcePack != null ?
                new BedrockFontGenerator() :
                null;
        for (FileUtils.ItemConfig config : configs) {
            ConfigurationSection glyphSection = config.config().getConfigurationSection("glyphs");
            ConfigurationSection guiSection = config.config().getConfigurationSection("guis");
            if (glyphSection != null) {
                for (String key : glyphSection.getKeys(false)) {
                    ConfigurationSection glyph = glyphSection.getConfigurationSection(key);
                    if (glyph == null) continue;
                    if (c >= 63743) throw new RuntimeException("Exceeded maximum number of glyphs (6400)");
                    String imagePath = glyph.getString("image_path");
                    if (imagePath == null) throw new RuntimeException("Missing image path for glyph: " + key);
                    if (!imagePath.endsWith(".png")) imagePath += ".png";
                    int ascent = glyph.getInt("ascent", 7);
                    int height = glyph.getInt("height", 8);
                    if (ascent > height) {
                        LostEngine.logger().warn("Glyph {} has ascent {} greater than height {}, please lower ascent in the glyph config in order for it to work.", key, ascent, height);
                        continue;
                    }

                    JsonObject providerObject = new JsonObject();
                    providerObject.addProperty("type", "bitmap");
                    providerObject.addProperty("file", "lost_engine" + ":" + imagePath);
                    providerObject.addProperty("ascent", ascent);
                    providerObject.addProperty("height", height);
                    JsonArray charsObject = new JsonArray();
                    String character = String.valueOf(c++);
                    charsObject.add(character);
                    providerObject.add("chars", charsObject);
                    providers.add(providerObject);
                    langFileGenerator.addTranslation("en_us", "glyph." + key, character, LangFileGenerator.Edition.JAVA);
                    if (bedrockFontGenerator != null) {
                        Texture texture = resourcePack.textures().get("assets/lost_engine/textures/" + imagePath);
                        if (texture != null) {
                            try (ByteArrayInputStream bais = new ByteArrayInputStream(texture.file().getBytes())) {
                                BufferedImage image = ImageIO.read(bais);
                                if (image.getWidth() < 1 || image.getHeight() < 1)
                                    throw new RuntimeException("Invalid image for glyph: " + key);
                                int width = (int) ((double) image.getWidth() / image.getHeight() * height);
                                if (height > 64 || width > 64) {
                                    LostEngine.logger().warn("Glyph {} is too large for bedrock font: {}x{}, please lower height in the glyph config in order for it to work.", key, width, height);
                                    continue;
                                }
                                BufferedImage resizedImage = FastBufferedImage.resizeImage(image, width, height);
                                int defaultAscent = height / 2 + 3; // compared to Minecraft Java, this is the ascent that Bedrock characters have
                                int ascentOffset = (defaultAscent - ascent) * 2;
                                if (ascentOffset != 0) {
                                    int newHeight = height + Math.abs(ascentOffset);
                                    if (newHeight > 64) {
                                        int maxOffset = (64 - height) / 2;
                                        LostEngine.logger().warn(
                                                "Ascent of glyph {} is too {} for bedrock font. Please set it between {} and {} (inclusive) or lower the height.",
                                                key, (ascentOffset > 0 ? "low" : "high"),
                                                defaultAscent - maxOffset, defaultAscent + maxOffset
                                        );
                                        continue;
                                    }
                                    BufferedImage newImage = new BufferedImage(width, newHeight, BufferedImage.TYPE_INT_ARGB);
                                    Graphics2D g = newImage.createGraphics();
                                    g.drawImage(resizedImage, 0, Math.max(0, ascentOffset), width, height, null);
                                    g.dispose();
                                    resizedImage = newImage;
                                }
                                // Set the opacity of the first and last pixel to at least 1
                                int firstPixel = resizedImage.getRGB(0, 0);
                                if (((firstPixel >> 24) & 0xFF) == 0) resizedImage.setRGB(0, 0, firstPixel | 0x01000000);
                                int lastPixel = resizedImage.getRGB(resizedImage.getWidth() - 1, resizedImage.getHeight() - 1);
                                if (((lastPixel >> 24) & 0xFF) == 0)
                                    resizedImage.setRGB(resizedImage.getWidth() - 1, resizedImage.getHeight() - 1, lastPixel | 0x01000000);
                                bedrockFontGenerator.addGlyph(key, resizedImage);
                            } catch (IOException e) {
                                LostEngine.logger().warn("Failed to parse texture for glyph: {}", key, e);
                            }
                        } else {
                            LostEngine.logger().warn("Glyph texture not found for glyph {}: {}", key, imagePath);
                        }
                    }
                }
            }
            if (guiSection != null) {
                for (String key : guiSection.getKeys(false)) {
                    ConfigurationSection gui = guiSection.getConfigurationSection(key);
                    if (gui == null) continue;
                    if (c >= 63743) throw new RuntimeException("Exceeded maximum number of glyphs (6400)");
                    String imagePath = gui.getString("image_path");
                    if (imagePath == null) throw new RuntimeException("Missing image path for glyph: " + key);
                    if (!imagePath.endsWith(".png")) imagePath += ".png";

                    JsonObject providerObject = new JsonObject();
                    providerObject.addProperty("type", "bitmap");
                    providerObject.addProperty("file", "lost_engine" + ":" + imagePath);
                    providerObject.addProperty("ascent", 13);
                    providerObject.addProperty("height", 221);
                    JsonArray charsObject = new JsonArray();
                    String character = String.valueOf(c++);
                    charsObject.add(character);
                    providerObject.add("chars", charsObject);
                    providers.add(providerObject);
                    langFileGenerator.addTranslation("en_us", "gui." + key, character, LangFileGenerator.Edition.JAVA);
                }
            }

        }
        if (bedrockFontGenerator != null) bedrockFontGenerator.build(bedrockResourcePack, langFileGenerator);
        JsonObject fontObject = new JsonObject();
        fontObject.add("providers", providers);
        resourcePack.jsonFile("assets/minecraft/font/default.json", fontObject);
    }

    private static void addTexturesRecursively(ResourcePack resourcePack, @Nullable BedrockResourcePack bedrockResourcePack, @NotNull File texturesDirectory, String namespace) {
        Path baseDir = texturesDirectory.toPath();
        try (Stream<@NotNull Path> paths = Files.walk(baseDir)) {
            paths.filter(path -> Files.isRegularFile(path) && path.toString().endsWith(".png"))
                    .forEach(path -> {
                        String textureKey = baseDir.relativize(path).toString().replace("\\", "/");
                        try {
                            resourcePack.texture(Texture.file("assets/" + namespace + "/textures/" + textureKey, path.toFile()));
                            if (bedrockResourcePack != null)
                                bedrockResourcePack.texture(Texture.file("textures/" + textureKey, path.toFile()));
                        } catch (IOException e) {
                            throw new RuntimeException(e);
                        }
                    });
        } catch (IOException e) {
            LostEngine.logger().error("Failed to add textures recursively", e);
        }
    }

    private static void createBlockModel(@NotNull JavaResourcePack resourcePack, @NotNull Key modelKey, @NotNull Key textureKey) {
        resourcePack.model(
                Model.model("assets/" + modelKey.namespace() + "/models/" + modelKey.value() + ".json")
                        .parent("block/cube_all")
                        .texture("all", textureKey.asString())
        );
    }

    private static void createItemModel(@NotNull JavaResourcePack resourcePack, @NotNull Key modelKey, @NotNull Key parent, @NotNull Key textureKey) {
        resourcePack.model(
                Model.model("assets/" + modelKey.namespace() + "/models/" + modelKey.value() + ".json")
                        .parent(parent.asString())
                        .texture("layer0", textureKey.asString())
        );
    }

    private static void createInHandTridentModel(@NotNull JavaResourcePack resourcePack, @NotNull Key modelKey, @NotNull Key textureKey) {
        Model.Display display = Model.Display.display();
        // This is not a 100% the same transformation as the trident, but the model is built-in I have no idea how to get it
        display.put(Model.Display.DisplayType.THIRDPERSON_RIGHTHAND, Model.Display.Transform.transform().rotation(new float[]{0, 60, 0}).translation(new float[]{0.25f, -2, 0.75f}).scale(new float[]{2, 2, 1}));
        display.put(Model.Display.DisplayType.THIRDPERSON_LEFTHAND, Model.Display.Transform.transform().rotation(new float[]{0, 60, 0}).translation(new float[]{0, -2, 1.5f}).scale(new float[]{2, 2, 1}));
        display.put(Model.Display.DisplayType.FIRSTPERSON_RIGHTHAND, Model.Display.Transform.transform().rotation(new float[]{0, -90, 25}).translation(new float[]{5.25f, -3.5f, 2}).scale(new float[]{2, 2, 1}));
        display.put(Model.Display.DisplayType.FIRSTPERSON_LEFTHAND, Model.Display.Transform.transform().rotation(new float[]{0, -90, 25}).translation(new float[]{4.25f, -3.75f, 2}).scale(new float[]{2, 2, 1}));
        resourcePack.model(
                Model.model("assets/" + modelKey.namespace() + "/models/" + modelKey.value() + ".json")
                        .parent("item/generated")
                        .texture("layer0", textureKey.asString())
                        .display(display)
        );
    }

    private static void createThrowingTridentModel(@NotNull JavaResourcePack resourcePack, @NotNull Key modelKey, @NotNull Key textureKey) {
        Model.Display display = Model.Display.display();
        // This is not a 100% the same transformation as the trident, but the model is built-in I have no idea how to get it
        display.put(Model.Display.DisplayType.THIRDPERSON_RIGHTHAND, Model.Display.Transform.transform().rotation(new float[]{180, -90, 0}).translation(new float[]{0.25f, -2, 0.75f}).scale(new float[]{2, 2, 1}));
        display.put(Model.Display.DisplayType.THIRDPERSON_LEFTHAND, Model.Display.Transform.transform().rotation(new float[]{180, -90, 0}).translation(new float[]{0, -2, 1.5f}).scale(new float[]{2, 2, 1}));
        display.put(Model.Display.DisplayType.FIRSTPERSON_RIGHTHAND, Model.Display.Transform.transform().rotation(new float[]{0, -90, 25}).translation(new float[]{5.25f, -3.5f, 2}).scale(new float[]{2, 2, 1}));
        display.put(Model.Display.DisplayType.FIRSTPERSON_LEFTHAND, Model.Display.Transform.transform().rotation(new float[]{0, -90, 25}).translation(new float[]{4.25f, -3.75f, 2}).scale(new float[]{2, 2, 1}));
        resourcePack.model(
                Model.model("assets/" + modelKey.namespace() + "/models/" + modelKey.value() + ".json")
                        .parent("item/generated")
                        .texture("layer0", textureKey.asString())
                        .display(display)
        );
    }

    private static void createItemFile(
            @NotNull ResourcePack resourcePack,
            @NotNull String path,
            @NotNull String modelKey,
            @Nullable PaintingItemJsonGenerator paintingItemJsonGenerator,
            @Nullable String paintingVariantKey
    ) {
        resourcePack.jsonFile(path, JsonParser.parseString("{\"model\":{\"type\":\"minecraft:model\",\"model\":\"%s\"}}".formatted(modelKey)));
        if (paintingItemJsonGenerator != null && paintingVariantKey != null)
            paintingItemJsonGenerator.addItem(paintingVariantKey, JsonParser.parseString("{\"type\":\"minecraft:model\",\"model\":\"%s\"}".formatted(modelKey)).getAsJsonObject());
    }

    private static void createTridentItemFile(
            @NotNull ResourcePack resourcePack,
            @NotNull String path,
            @NotNull String iconModelKey,
            @NotNull String throwingModelKey,
            @NotNull String inHandModelKey,
            @Nullable PaintingItemJsonGenerator paintingItemJsonGenerator,
            @Nullable String paintingVariantKey
    ) {
        resourcePack.jsonFile(
                path,
                JsonParser.parseString("{\"model\":{\"type\":\"minecraft:select\",\"cases\":[{\"model\":{\"type\":\"minecraft:model\",\"model\":\"%s\"},\"when\":[\"gui\",\"ground\",\"on_shelf\"]}],\"fallback\":{\"type\":\"minecraft:condition\",\"on_true\":{\"type\":\"minecraft:model\",\"model\":\"%s\"},\"on_false\":{\"type\":\"minecraft:model\",\"model\":\"%s\"},\"property\":\"minecraft:using_item\"},\"property\":\"minecraft:display_context\"}}"
                        .formatted(iconModelKey, throwingModelKey, inHandModelKey)
                )
        );
        if (paintingItemJsonGenerator != null && paintingVariantKey != null)
            paintingItemJsonGenerator.addItem(paintingVariantKey, JsonParser.parseString("{\"type\":\"minecraft:model\",\"model\":\"%s\"}".formatted(iconModelKey)).getAsJsonObject());
    }

    private static void createBedrockTextureData(@NotNull BedrockResourcePack bedrockResourcePack, @Pattern("^textures/([a-zA-Z0-9_\\-/]+$)") String texturePath, @NotNull String itemName) {
        UnknownFile file = bedrockResourcePack.unknownFiles().get("textures/item_texture.json");
        String text = file != null ? file.file().getText() : "{\"texture_data\":{}}";
        JsonObject json = JsonParser.parseString(text).getAsJsonObject();
        JsonObject textureData = json.getAsJsonObject("texture_data");
        JsonObject item = new JsonObject();
        item.addProperty("textures", texturePath);
        textureData.add("lost_engine_" + itemName, item);
        bedrockResourcePack.unknownFile(UnknownFile.utf8("textures/item_texture.json", json.toString()));
    }

}
